# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_form2.ui'
#
# Created: Sat Dec 28 23:32:57 2013
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(600, 420)
        Form.setMinimumSize(QtCore.QSize(600, 420))
        Form.setMaximumSize(QtCore.QSize(600, 420))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/flowmapper/icon2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setModal(True)
        self.buttonBox = QtGui.QDialogButtonBox(Form)
        self.buttonBox.setGeometry(QtCore.QRect(420, 380, 160, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.BrowseShapeInputFilter = QtGui.QPushButton(Form)
        self.BrowseShapeInputFilter.setGeometry(QtCore.QRect(510, 10, 75, 24))
        self.BrowseShapeInputFilter.setObjectName(_fromUtf8("BrowseShapeInputFilter"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 270, 201, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 230, 180, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.BrowseShapeLineEdit = QtGui.QLineEdit(Form)
        self.BrowseShapeLineEdit.setEnabled(False)
        self.BrowseShapeLineEdit.setGeometry(QtCore.QRect(198, 10, 301, 20))
        self.BrowseShapeLineEdit.setText(_fromUtf8(""))
        self.BrowseShapeLineEdit.setObjectName(_fromUtf8("BrowseShapeLineEdit"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 131, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.No_Of_Features_LineEdit = QtGui.QLineEdit(Form)
        self.No_Of_Features_LineEdit.setGeometry(QtCore.QRect(200, 100, 60, 20))
        self.No_Of_Features_LineEdit.setReadOnly(True)
        self.No_Of_Features_LineEdit.setObjectName(_fromUtf8("No_Of_Features_LineEdit"))
        self.BrowseShapeOutputFilter = QtGui.QPushButton(Form)
        self.BrowseShapeOutputFilter.setGeometry(QtCore.QRect(510, 230, 75, 24))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BrowseShapeOutputFilter.sizePolicy().hasHeightForWidth())
        self.BrowseShapeOutputFilter.setSizePolicy(sizePolicy)
        self.BrowseShapeOutputFilter.setObjectName(_fromUtf8("BrowseShapeOutputFilter"))
        self.Mean_LineEdit = QtGui.QLineEdit(Form)
        self.Mean_LineEdit.setGeometry(QtCore.QRect(200, 130, 60, 20))
        self.Mean_LineEdit.setText(_fromUtf8(""))
        self.Mean_LineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Mean_LineEdit.setReadOnly(True)
        self.Mean_LineEdit.setObjectName(_fromUtf8("Mean_LineEdit"))
        self.Filter_LineEdit = QtGui.QLineEdit(Form)
        self.Filter_LineEdit.setGeometry(QtCore.QRect(330, 270, 61, 20))
        self.Filter_LineEdit.setObjectName(_fromUtf8("Filter_LineEdit"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 161, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_01 = QtGui.QLabel(Form)
        self.label_01.setGeometry(QtCore.QRect(10, 10, 180, 20))
        self.label_01.setObjectName(_fromUtf8("label_01"))
        self.CalStat = QtGui.QPushButton(Form)
        self.CalStat.setEnabled(True)
        self.CalStat.setGeometry(QtCore.QRect(319, 70, 261, 24))
        self.CalStat.setObjectName(_fromUtf8("CalStat"))
        self.BrowseShapeLineEdit_2 = QtGui.QLineEdit(Form)
        self.BrowseShapeLineEdit_2.setEnabled(False)
        self.BrowseShapeLineEdit_2.setGeometry(QtCore.QRect(200, 230, 301, 20))
        self.BrowseShapeLineEdit_2.setText(_fromUtf8(""))
        self.BrowseShapeLineEdit_2.setObjectName(_fromUtf8("BrowseShapeLineEdit_2"))
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 101, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.StdDev_LineEdit = QtGui.QLineEdit(Form)
        self.StdDev_LineEdit.setGeometry(QtCore.QRect(200, 160, 60, 20))
        self.StdDev_LineEdit.setText(_fromUtf8(""))
        self.StdDev_LineEdit.setReadOnly(True)
        self.StdDev_LineEdit.setObjectName(_fromUtf8("StdDev_LineEdit"))
        self.MeanNotZero_LineEdit = QtGui.QLineEdit(Form)
        self.MeanNotZero_LineEdit.setGeometry(QtCore.QRect(520, 130, 60, 20))
        self.MeanNotZero_LineEdit.setText(_fromUtf8(""))
        self.MeanNotZero_LineEdit.setReadOnly(True)
        self.MeanNotZero_LineEdit.setObjectName(_fromUtf8("MeanNotZero_LineEdit"))
        self.No_Of_ZeroFlowFeatures_LineEdit = QtGui.QLineEdit(Form)
        self.No_Of_ZeroFlowFeatures_LineEdit.setGeometry(QtCore.QRect(520, 100, 60, 20))
        self.No_Of_ZeroFlowFeatures_LineEdit.setReadOnly(True)
        self.No_Of_ZeroFlowFeatures_LineEdit.setObjectName(_fromUtf8("No_Of_ZeroFlowFeatures_LineEdit"))
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(320, 100, 151, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.SumMagnitude_LineEdit = QtGui.QLineEdit(Form)
        self.SumMagnitude_LineEdit.setGeometry(QtCore.QRect(200, 70, 60, 20))
        self.SumMagnitude_LineEdit.setReadOnly(True)
        self.SumMagnitude_LineEdit.setObjectName(_fromUtf8("SumMagnitude_LineEdit"))
        self.label_8 = QtGui.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(10, 70, 181, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(320, 130, 191, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.StdDevNotZero_LineEdit = QtGui.QLineEdit(Form)
        self.StdDevNotZero_LineEdit.setGeometry(QtCore.QRect(520, 160, 60, 20))
        self.StdDevNotZero_LineEdit.setText(_fromUtf8(""))
        self.StdDevNotZero_LineEdit.setReadOnly(True)
        self.StdDevNotZero_LineEdit.setObjectName(_fromUtf8("StdDevNotZero_LineEdit"))
        self.label_10 = QtGui.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(320, 160, 161, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.MaxFlow_LineEdit = QtGui.QLineEdit(Form)
        self.MaxFlow_LineEdit.setGeometry(QtCore.QRect(200, 190, 60, 20))
        self.MaxFlow_LineEdit.setText(_fromUtf8(""))
        self.MaxFlow_LineEdit.setReadOnly(True)
        self.MaxFlow_LineEdit.setObjectName(_fromUtf8("MaxFlow_LineEdit"))
        self.label_11 = QtGui.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(10, 190, 111, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(400, 270, 31, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.MinFlow_LineEdit = QtGui.QLineEdit(Form)
        self.MinFlow_LineEdit.setGeometry(QtCore.QRect(520, 190, 60, 20))
        self.MinFlow_LineEdit.setText(_fromUtf8(""))
        self.MinFlow_LineEdit.setReadOnly(True)
        self.MinFlow_LineEdit.setObjectName(_fromUtf8("MinFlow_LineEdit"))
        self.label_13 = QtGui.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(320, 190, 171, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.Magnitude_comboBox = QtGui.QComboBox(Form)
        self.Magnitude_comboBox.setGeometry(QtCore.QRect(220, 270, 101, 22))
        self.Magnitude_comboBox.setObjectName(_fromUtf8("Magnitude_comboBox"))
        self.Magnitude_comboBox.addItem(_fromUtf8(""))
        self.Magnitude_comboBox.addItem(_fromUtf8(""))
        self.Magnitude_comboBox.addItem(_fromUtf8(""))
        self.Magnitude_comboBox.addItem(_fromUtf8(""))
        self.Magnitude_comboBox.addItem(_fromUtf8(""))
        self.label_15 = QtGui.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(200, 40, 391, 20))
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.lineEditInterval = QtGui.QLineEdit(Form)
        self.lineEditInterval.setEnabled(False)
        self.lineEditInterval.setGeometry(QtCore.QRect(280, 340, 51, 20))
        self.lineEditInterval.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditInterval.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditInterval.setObjectName(_fromUtf8("lineEditInterval"))
        self.spinBoxClasses = QtGui.QSpinBox(Form)
        self.spinBoxClasses.setEnabled(False)
        self.spinBoxClasses.setGeometry(QtCore.QRect(90, 340, 51, 22))
        self.spinBoxClasses.setMinimum(2)
        self.spinBoxClasses.setProperty(_fromUtf8("value"), 2)
        self.spinBoxClasses.setObjectName(_fromUtf8("spinBoxClasses"))
        self.label_16 = QtGui.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(10, 340, 81, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.comboBoxSelectSymbology = QtGui.QComboBox(Form)
        self.comboBoxSelectSymbology.setEnabled(True)
        self.comboBoxSelectSymbology.setGeometry(QtCore.QRect(460, 310, 120, 22))
        self.comboBoxSelectSymbology.setObjectName(_fromUtf8("comboBoxSelectSymbology"))
        self.comboBoxSelectSymbology.addItem(_fromUtf8(""))
        self.comboBoxSelectSymbology.addItem(_fromUtf8(""))
        self.comboBoxSelectSymbology.addItem(_fromUtf8(""))
        self.comboBoxSelectSymbology.addItem(_fromUtf8(""))
        self.comboBoxSelectSymbology.addItem(_fromUtf8(""))
        self.comboBoxSelectStdDev = QtGui.QComboBox(Form)
        self.comboBoxSelectStdDev.setEnabled(False)
        self.comboBoxSelectStdDev.setGeometry(QtCore.QRect(460, 340, 120, 22))
        self.comboBoxSelectStdDev.setObjectName(_fromUtf8("comboBoxSelectStdDev"))
        self.comboBoxSelectStdDev.addItem(_fromUtf8(""))
        self.comboBoxSelectStdDev.addItem(_fromUtf8(""))
        self.comboBoxSelectStdDev.addItem(_fromUtf8(""))
        self.comboBoxSelectStdDev.addItem(_fromUtf8(""))
        self.label_17 = QtGui.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(380, 340, 81, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.Add2MapcheckBox = QtGui.QCheckBox(Form)
        self.Add2MapcheckBox.setEnabled(True)
        self.Add2MapcheckBox.setGeometry(QtCore.QRect(10, 310, 231, 17))
        self.Add2MapcheckBox.setChecked(True)
        self.Add2MapcheckBox.setObjectName(_fromUtf8("Add2MapcheckBox"))
        self.label_18 = QtGui.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(200, 340, 81, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.ShowDirectioncheckBox = QtGui.QCheckBox(Form)
        self.ShowDirectioncheckBox.setEnabled(True)
        self.ShowDirectioncheckBox.setGeometry(QtCore.QRect(280, 310, 121, 17))
        self.ShowDirectioncheckBox.setChecked(True)
        self.ShowDirectioncheckBox.setObjectName(_fromUtf8("ShowDirectioncheckBox"))

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Form.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Form.reject)
        
        ##--------------------------------------------------------##
        ##--------------------------------------------------------##        
        QtCore.QObject.connect(self.Add2MapcheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.comboBoxSelectSymbology.setEnabled)
        QtCore.QObject.connect(self.Add2MapcheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.reset_enable_disable_state)
        #QtCore.QObject.connect(self.Add2MapcheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.uncheck_ShowDirectioncheckBox)
        QtCore.QObject.connect(self.comboBoxSelectSymbology, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.enable_disable)
        ##--------------------------------------------------------##
        ##--------------------------------------------------------##
        
        QtCore.QMetaObject.connectSlotsByName(Form)
        
        Form.setTabOrder(self.BrowseShapeLineEdit, self.BrowseShapeInputFilter)
        Form.setTabOrder(self.BrowseShapeInputFilter, self.CalStat)
        Form.setTabOrder(self.CalStat, self.SumMagnitude_LineEdit)
        Form.setTabOrder(self.SumMagnitude_LineEdit, self.No_Of_Features_LineEdit)
        Form.setTabOrder(self.No_Of_Features_LineEdit, self.Mean_LineEdit)
        Form.setTabOrder(self.Mean_LineEdit, self.StdDev_LineEdit)
        Form.setTabOrder(self.StdDev_LineEdit, self.MaxFlow_LineEdit)
        Form.setTabOrder(self.MaxFlow_LineEdit, self.No_Of_ZeroFlowFeatures_LineEdit)
        Form.setTabOrder(self.No_Of_ZeroFlowFeatures_LineEdit, self.MeanNotZero_LineEdit)
        Form.setTabOrder(self.MeanNotZero_LineEdit, self.StdDevNotZero_LineEdit)
        Form.setTabOrder(self.StdDevNotZero_LineEdit, self.MinFlow_LineEdit)
        Form.setTabOrder(self.MinFlow_LineEdit, self.BrowseShapeLineEdit_2)
        Form.setTabOrder(self.BrowseShapeLineEdit_2, self.BrowseShapeOutputFilter)
        Form.setTabOrder(self.BrowseShapeOutputFilter, self.Magnitude_comboBox)
        Form.setTabOrder(self.Magnitude_comboBox, self.Filter_LineEdit)
        Form.setTabOrder(self.Filter_LineEdit, self.Add2MapcheckBox)
        Form.setTabOrder(self.Add2MapcheckBox, self.ShowDirectioncheckBox)
        Form.setTabOrder(self.ShowDirectioncheckBox, self.comboBoxSelectSymbology)
        Form.setTabOrder(self.comboBoxSelectSymbology, self.spinBoxClasses)
        Form.setTabOrder(self.spinBoxClasses, self.lineEditInterval)
        Form.setTabOrder(self.lineEditInterval, self.comboBoxSelectStdDev)
        Form.setTabOrder(self.comboBoxSelectStdDev, self.buttonBox)
        
    ##--------------------------------------------------------##
    ##--------------------------------------------------------##
    def reset_enable_disable_state(self):
        self.comboBoxSelectSymbology.setCurrentIndex(0)
        self.spinBoxClasses.setEnabled(False)
        self.lineEditInterval.setEnabled(False)
        self.comboBoxSelectStdDev.setEnabled(False)
        
        if self.Add2MapcheckBox.isChecked() == True:
            self.ShowDirectioncheckBox.setEnabled(True)
            self.ShowDirectioncheckBox.setChecked(True)
        elif self.Add2MapcheckBox.isChecked() == False:
            self.ShowDirectioncheckBox.setEnabled(False)
            self.ShowDirectioncheckBox.setChecked(False)        
        
    def enable_disable(self):
        if self.comboBoxSelectSymbology.currentText() == "Single Symbol":
            self.spinBoxClasses.setEnabled(False)
            self.lineEditInterval.setEnabled(False)
            self.comboBoxSelectStdDev.setEnabled(False)
            if self.Add2MapcheckBox.isChecked() == True:
                self.ShowDirectioncheckBox.setEnabled(True)
                self.ShowDirectioncheckBox.setChecked(True)
            elif self.Add2MapcheckBox.isChecked() == False:
                self.ShowDirectioncheckBox.setEnabled(False)
                self.ShowDirectioncheckBox.setChecked(False)            
            
        elif self.comboBoxSelectSymbology.currentText() == "Equal Size Classes":
            self.spinBoxClasses.setEnabled(True)
            self.lineEditInterval.setEnabled(False)
            self.comboBoxSelectStdDev.setEnabled(False)
            if self.Add2MapcheckBox.isChecked() == True:
                self.ShowDirectioncheckBox.setEnabled(True)
                self.ShowDirectioncheckBox.setChecked(True)
            elif self.Add2MapcheckBox.isChecked() == False:
                self.ShowDirectioncheckBox.setEnabled(False)
                self.ShowDirectioncheckBox.setChecked(False)
            
        elif self.comboBoxSelectSymbology.currentText() == "Equal Interval":
            self.spinBoxClasses.setEnabled(True)
            self.lineEditInterval.setEnabled(False)
            self.comboBoxSelectStdDev.setEnabled(False)  
            if self.Add2MapcheckBox.isChecked() == True:            
                self.ShowDirectioncheckBox.setEnabled(True)            
                self.ShowDirectioncheckBox.setChecked(True)            
            elif self.Add2MapcheckBox.isChecked() == False:            
                self.ShowDirectioncheckBox.setEnabled(False)            
                self.ShowDirectioncheckBox.setChecked(False)            
            
        elif self.comboBoxSelectSymbology.currentText() == "Defined Interval":
            self.spinBoxClasses.setEnabled(False)
            self.lineEditInterval.setEnabled(True)
            self.comboBoxSelectStdDev.setEnabled(False) 
            if self.Add2MapcheckBox.isChecked() == True:
                self.ShowDirectioncheckBox.setEnabled(True)
                self.ShowDirectioncheckBox.setChecked(True)
            elif self.Add2MapcheckBox.isChecked() == False:
                self.ShowDirectioncheckBox.setEnabled(False)
                self.ShowDirectioncheckBox.setChecked(False)
            
        elif self.comboBoxSelectSymbology.currentText() == "Standard Deviation":
            self.spinBoxClasses.setEnabled(False)
            self.lineEditInterval.setEnabled(False)
            self.comboBoxSelectStdDev.setEnabled(True)  
            if self.Add2MapcheckBox.isChecked() == True:
                self.ShowDirectioncheckBox.setEnabled(True)
                self.ShowDirectioncheckBox.setChecked(True)
            elif self.Add2MapcheckBox.isChecked() == False:
                self.ShowDirectioncheckBox.setEnabled(False)            
                self.ShowDirectioncheckBox.setChecked(False)    
                
    def uncheck_ShowDirectioncheckBox(self):
        self.ShowDirectioncheckBox.setChecked(False)            
    ##--------------------------------------------------------##
    ##--------------------------------------------------------##
    
    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Filter flow lines by magnitude", None, QtGui.QApplication.UnicodeUTF8))
        self.BrowseShapeInputFilter.setText(QtGui.QApplication.translate("Form", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Delete flow lines having magnitude", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Output location for filtered shapefile :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Average flow magnitude :", None, QtGui.QApplication.UnicodeUTF8))
        self.BrowseShapeOutputFilter.setText(QtGui.QApplication.translate("Form", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.Filter_LineEdit.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Number of flow lines in shapefile :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_01.setText(QtGui.QApplication.translate("Form", "Select shapefile storing flow lines :", None, QtGui.QApplication.UnicodeUTF8))
        self.CalStat.setText(QtGui.QApplication.translate("Form", "Calculate Statistics...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Standard deviation :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Number of zero flow features :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Total magnitude of flows in shapefile :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Avg. magnitude excluding zero flows :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "Std. Dev. excluding zero flows :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Maximum flow :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Form", "flows", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Form", "Minimum flow excluding zero flows :", None, QtGui.QApplication.UnicodeUTF8))
        self.Magnitude_comboBox.setItemText(0, QtGui.QApplication.translate("Form", "less than <", None, QtGui.QApplication.UnicodeUTF8))
        self.Magnitude_comboBox.setItemText(1, QtGui.QApplication.translate("Form", "<=", None, QtGui.QApplication.UnicodeUTF8))
        self.Magnitude_comboBox.setItemText(2, QtGui.QApplication.translate("Form", "equal to =", None, QtGui.QApplication.UnicodeUTF8))
        self.Magnitude_comboBox.setItemText(3, QtGui.QApplication.translate("Form", ">=", None, QtGui.QApplication.UnicodeUTF8))
        self.Magnitude_comboBox.setItemText(4, QtGui.QApplication.translate("Form", "greater than >", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "* Input shapefile must be created with Flow Mapper or include \"magnitude\" field.", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditInterval.setText(QtGui.QApplication.translate("Form", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "No. of classes :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectSymbology.setItemText(0, QtGui.QApplication.translate("Form", "Single Symbol", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectSymbology.setItemText(1, QtGui.QApplication.translate("Form", "Equal Size Classes", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectSymbology.setItemText(2, QtGui.QApplication.translate("Form", "Equal Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectSymbology.setItemText(3, QtGui.QApplication.translate("Form", "Defined Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectSymbology.setItemText(4, QtGui.QApplication.translate("Form", "Standard Deviation", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectStdDev.setItemText(0, QtGui.QApplication.translate("Form", "1/4 Std. Dev.", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectStdDev.setItemText(1, QtGui.QApplication.translate("Form", "1/2 Std. Dev.", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectStdDev.setItemText(2, QtGui.QApplication.translate("Form", "1 Std. Dev.", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectStdDev.setItemText(3, QtGui.QApplication.translate("Form", "2 Std. Dev.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "Class Interval :", None, QtGui.QApplication.UnicodeUTF8))
        self.Add2MapcheckBox.setText(QtGui.QApplication.translate("Form", "Add shapefile to map canvas after filtering", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "Class interval :", None, QtGui.QApplication.UnicodeUTF8))
        self.ShowDirectioncheckBox.setText(QtGui.QApplication.translate("Form", "Show flow direction", None, QtGui.QApplication.UnicodeUTF8))

import resources
