# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_form4.ui'
#
# Created: Sun Nov 24 05:37:06 2013
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(580, 345)
        Form.setMinimumSize(QtCore.QSize(580, 345))
        Form.setMaximumSize(QtCore.QSize(580, 345))        
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/flowmapper/icon5.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setModal(True)
        self.lineEditMinSymbology = QtGui.QLineEdit(Form)
        self.lineEditMinSymbology.setGeometry(QtCore.QRect(60, 90, 51, 20))
        self.lineEditMinSymbology.setReadOnly(True)
        self.lineEditMinSymbology.setObjectName(_fromUtf8("lineEditMinSymbology"))
        self.PushButtonColorSelect_3 = QtGui.QPushButton(Form)
        self.PushButtonColorSelect_3.setEnabled(False)
        self.PushButtonColorSelect_3.setGeometry(QtCore.QRect(210, 230, 51, 23))
        self.PushButtonColorSelect_3.setObjectName(_fromUtf8("PushButtonColorSelect_3"))
        self.label_15 = QtGui.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(170, 50, 391, 20))
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_31 = QtGui.QLabel(Form)
        self.label_31.setGeometry(QtCore.QRect(440, 90, 71, 20))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.comboBoxSelectSymbology = QtGui.QComboBox(Form)
        self.comboBoxSelectSymbology.setEnabled(True)
        self.comboBoxSelectSymbology.setGeometry(QtCore.QRect(440, 130, 121, 22))
        self.comboBoxSelectSymbology.setObjectName(_fromUtf8("comboBoxSelectSymbology"))
        self.comboBoxSelectSymbology.addItem(_fromUtf8(""))
        self.comboBoxSelectSymbology.addItem(_fromUtf8(""))
        self.comboBoxSelectSymbology.addItem(_fromUtf8(""))
        self.comboBoxSelectSymbology.addItem(_fromUtf8(""))
        self.comboBoxSelectSymbology.addItem(_fromUtf8(""))
        self.comboBoxSelectSymbology.addItem(_fromUtf8(""))
        self.PushButtonColorSelect_7 = QtGui.QPushButton(Form)
        self.PushButtonColorSelect_7.setEnabled(False)
        self.PushButtonColorSelect_7.setGeometry(QtCore.QRect(450, 230, 51, 23))
        self.PushButtonColorSelect_7.setObjectName(_fromUtf8("PushButtonColorSelect_7"))
        self.label_33 = QtGui.QLabel(Form)
        self.label_33.setGeometry(QtCore.QRect(20, 260, 61, 20))
        self.label_33.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.lineEditInterval = QtGui.QLineEdit(Form)
        self.lineEditInterval.setEnabled(False)
        self.lineEditInterval.setGeometry(QtCore.QRect(270, 160, 51, 20))
        self.lineEditInterval.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditInterval.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditInterval.setObjectName(_fromUtf8("lineEditInterval"))
        self.lineEditMaxSymbology = QtGui.QLineEdit(Form)
        self.lineEditMaxSymbology.setGeometry(QtCore.QRect(160, 90, 51, 20))
        self.lineEditMaxSymbology.setReadOnly(True)
        self.lineEditMaxSymbology.setObjectName(_fromUtf8("lineEditMaxSymbology"))
        self.lineEditManualInterval_5 = QtGui.QLineEdit(Form)
        self.lineEditManualInterval_5.setEnabled(False)
        self.lineEditManualInterval_5.setGeometry(QtCore.QRect(330, 200, 51, 20))
        self.lineEditManualInterval_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditManualInterval_5.setText(_fromUtf8(""))
        self.lineEditManualInterval_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditManualInterval_5.setObjectName(_fromUtf8("lineEditManualInterval_5"))
        self.doubleSpinBoxThickness_8 = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBoxThickness_8.setEnabled(False)
        self.doubleSpinBoxThickness_8.setGeometry(QtCore.QRect(510, 260, 51, 22))
        self.doubleSpinBoxThickness_8.setSingleStep(0.25)
        self.doubleSpinBoxThickness_8.setProperty(_fromUtf8("value"), 6.0)
        self.doubleSpinBoxThickness_8.setObjectName(_fromUtf8("doubleSpinBoxThickness_8"))
        self.PushButtonColorSelect_8 = QtGui.QPushButton(Form)
        self.PushButtonColorSelect_8.setEnabled(False)
        self.PushButtonColorSelect_8.setGeometry(QtCore.QRect(510, 230, 51, 23))
        self.PushButtonColorSelect_8.setObjectName(_fromUtf8("PushButtonColorSelect_8"))
        self.doubleSpinBoxThickness_2 = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBoxThickness_2.setEnabled(False)
        self.doubleSpinBoxThickness_2.setGeometry(QtCore.QRect(150, 260, 51, 22))
        self.doubleSpinBoxThickness_2.setSingleStep(0.25)
        self.doubleSpinBoxThickness_2.setProperty(_fromUtf8("value"), 0.5)
        self.doubleSpinBoxThickness_2.setObjectName(_fromUtf8("doubleSpinBoxThickness_2"))
        self.doubleSpinBoxThickness_3 = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBoxThickness_3.setEnabled(False)
        self.doubleSpinBoxThickness_3.setGeometry(QtCore.QRect(210, 260, 51, 22))
        self.doubleSpinBoxThickness_3.setSingleStep(0.25)
        self.doubleSpinBoxThickness_3.setProperty(_fromUtf8("value"), 1.0)
        self.doubleSpinBoxThickness_3.setObjectName(_fromUtf8("doubleSpinBoxThickness_3"))
        self.label_28 = QtGui.QLabel(Form)
        self.label_28.setGeometry(QtCore.QRect(320, 90, 61, 20))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.buttonBox = QtGui.QDialogButtonBox(Form)
        self.buttonBox.setGeometry(QtCore.QRect(390, 300, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.doubleSpinBoxThickness_1 = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBoxThickness_1.setEnabled(False)
        self.doubleSpinBoxThickness_1.setGeometry(QtCore.QRect(90, 260, 51, 22))
        self.doubleSpinBoxThickness_1.setSingleStep(0.25)
        self.doubleSpinBoxThickness_1.setProperty(_fromUtf8("value"), 0.25)
        self.doubleSpinBoxThickness_1.setObjectName(_fromUtf8("doubleSpinBoxThickness_1"))
        self.PushButtonColorSelect_6 = QtGui.QPushButton(Form)
        self.PushButtonColorSelect_6.setEnabled(False)
        self.PushButtonColorSelect_6.setGeometry(QtCore.QRect(390, 230, 51, 23))
        self.PushButtonColorSelect_6.setObjectName(_fromUtf8("PushButtonColorSelect_6"))
        self.lineEditManualInterval_6 = QtGui.QLineEdit(Form)
        self.lineEditManualInterval_6.setEnabled(False)
        self.lineEditManualInterval_6.setGeometry(QtCore.QRect(390, 200, 51, 20))
        self.lineEditManualInterval_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditManualInterval_6.setText(_fromUtf8(""))
        self.lineEditManualInterval_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditManualInterval_6.setObjectName(_fromUtf8("lineEditManualInterval_6"))
        self.lineEditManualInterval_8 = QtGui.QLineEdit(Form)
        self.lineEditManualInterval_8.setEnabled(False)
        self.lineEditManualInterval_8.setGeometry(QtCore.QRect(510, 200, 51, 20))
        self.lineEditManualInterval_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditManualInterval_8.setText(_fromUtf8(""))
        self.lineEditManualInterval_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditManualInterval_8.setObjectName(_fromUtf8("lineEditManualInterval_8"))
        self.PushButtonColorSelect_4 = QtGui.QPushButton(Form)
        self.PushButtonColorSelect_4.setEnabled(False)
        self.PushButtonColorSelect_4.setGeometry(QtCore.QRect(270, 230, 51, 23))
        self.PushButtonColorSelect_4.setObjectName(_fromUtf8("PushButtonColorSelect_4"))
        self.label_16 = QtGui.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(20, 160, 81, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.lineEditManualInterval_1 = QtGui.QLineEdit(Form)
        self.lineEditManualInterval_1.setEnabled(False)
        self.lineEditManualInterval_1.setGeometry(QtCore.QRect(90, 200, 51, 20))
        self.lineEditManualInterval_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditManualInterval_1.setText(_fromUtf8(""))
        self.lineEditManualInterval_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditManualInterval_1.setObjectName(_fromUtf8("lineEditManualInterval_1"))
        self.label_29 = QtGui.QLabel(Form)
        self.label_29.setGeometry(QtCore.QRect(20, 90, 51, 20))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.lineEditManualInterval_3 = QtGui.QLineEdit(Form)
        self.lineEditManualInterval_3.setEnabled(False)
        self.lineEditManualInterval_3.setGeometry(QtCore.QRect(210, 200, 51, 20))
        self.lineEditManualInterval_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditManualInterval_3.setText(_fromUtf8(""))
        self.lineEditManualInterval_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditManualInterval_3.setObjectName(_fromUtf8("lineEditManualInterval_3"))
        self.lineEditStdDevSymbology = QtGui.QLineEdit(Form)
        self.lineEditStdDevSymbology.setGeometry(QtCore.QRect(380, 90, 51, 20))
        self.lineEditStdDevSymbology.setReadOnly(True)
        self.lineEditStdDevSymbology.setObjectName(_fromUtf8("lineEditStdDevSymbology"))
        self.label_17 = QtGui.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(360, 160, 81, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.doubleSpinBoxThickness_5 = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBoxThickness_5.setEnabled(False)
        self.doubleSpinBoxThickness_5.setGeometry(QtCore.QRect(330, 260, 51, 22))
        self.doubleSpinBoxThickness_5.setSingleStep(0.25)
        self.doubleSpinBoxThickness_5.setProperty(_fromUtf8("value"), 3.0)
        self.doubleSpinBoxThickness_5.setObjectName(_fromUtf8("doubleSpinBoxThickness_5"))
        self.label_01 = QtGui.QLabel(Form)
        self.label_01.setGeometry(QtCore.QRect(20, 20, 180, 20))
        self.label_01.setObjectName(_fromUtf8("label_01"))
        self.PushButtonColorSelect_2 = QtGui.QPushButton(Form)
        self.PushButtonColorSelect_2.setEnabled(False)
        self.PushButtonColorSelect_2.setGeometry(QtCore.QRect(150, 230, 51, 23))
        self.PushButtonColorSelect_2.setObjectName(_fromUtf8("PushButtonColorSelect_2"))
        self.label_30 = QtGui.QLabel(Form)
        self.label_30.setGeometry(QtCore.QRect(220, 90, 51, 20))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.BrowseShapeLineEdit = QtGui.QLineEdit(Form)
        self.BrowseShapeLineEdit.setEnabled(False)
        self.BrowseShapeLineEdit.setGeometry(QtCore.QRect(188, 20, 291, 20))
        self.BrowseShapeLineEdit.setText(_fromUtf8(""))
        self.BrowseShapeLineEdit.setObjectName(_fromUtf8("BrowseShapeLineEdit"))
        self.PushButtonColorSelect_1 = QtGui.QPushButton(Form)
        self.PushButtonColorSelect_1.setEnabled(False)
        self.PushButtonColorSelect_1.setGeometry(QtCore.QRect(90, 230, 51, 23))
        self.PushButtonColorSelect_1.setObjectName(_fromUtf8("PushButtonColorSelect_1"))
        self.lineEditManualInterval_7 = QtGui.QLineEdit(Form)
        self.lineEditManualInterval_7.setEnabled(False)
        self.lineEditManualInterval_7.setGeometry(QtCore.QRect(450, 200, 51, 20))
        self.lineEditManualInterval_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditManualInterval_7.setText(_fromUtf8(""))
        self.lineEditManualInterval_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditManualInterval_7.setObjectName(_fromUtf8("lineEditManualInterval_7"))
        self.label_27 = QtGui.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(120, 90, 51, 20))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.lineEditNoOfFeaturesSymbology = QtGui.QLineEdit(Form)
        self.lineEditNoOfFeaturesSymbology.setGeometry(QtCore.QRect(510, 90, 51, 20))
        self.lineEditNoOfFeaturesSymbology.setReadOnly(True)
        self.lineEditNoOfFeaturesSymbology.setObjectName(_fromUtf8("lineEditNoOfFeaturesSymbology"))
        self.lineEditMeanSymbology = QtGui.QLineEdit(Form)
        self.lineEditMeanSymbology.setGeometry(QtCore.QRect(260, 90, 51, 20))
        self.lineEditMeanSymbology.setReadOnly(True)
        self.lineEditMeanSymbology.setObjectName(_fromUtf8("lineEditMeanSymbology"))
        self.doubleSpinBoxThickness_4 = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBoxThickness_4.setEnabled(False)
        self.doubleSpinBoxThickness_4.setGeometry(QtCore.QRect(270, 260, 51, 22))
        self.doubleSpinBoxThickness_4.setSingleStep(0.25)
        self.doubleSpinBoxThickness_4.setProperty(_fromUtf8("value"), 2.0)
        self.doubleSpinBoxThickness_4.setObjectName(_fromUtf8("doubleSpinBoxThickness_4"))
        self.PushButtonColorSelect_5 = QtGui.QPushButton(Form)
        self.PushButtonColorSelect_5.setEnabled(False)
        self.PushButtonColorSelect_5.setGeometry(QtCore.QRect(330, 230, 51, 23))
        self.PushButtonColorSelect_5.setObjectName(_fromUtf8("PushButtonColorSelect_5"))
        self.label_19 = QtGui.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(20, 200, 71, 20))
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.spinBoxClasses = QtGui.QSpinBox(Form)
        self.spinBoxClasses.setEnabled(False)
        self.spinBoxClasses.setGeometry(QtCore.QRect(100, 160, 51, 22))
        self.spinBoxClasses.setMinimum(2)
        self.spinBoxClasses.setProperty(_fromUtf8("value"), 2)
        self.spinBoxClasses.setObjectName(_fromUtf8("spinBoxClasses"))
        self.lineEditManualInterval_2 = QtGui.QLineEdit(Form)
        self.lineEditManualInterval_2.setEnabled(False)
        self.lineEditManualInterval_2.setGeometry(QtCore.QRect(150, 200, 51, 20))
        self.lineEditManualInterval_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditManualInterval_2.setText(_fromUtf8(""))
        self.lineEditManualInterval_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditManualInterval_2.setObjectName(_fromUtf8("lineEditManualInterval_2"))
        self.BrowseShapeInputSymbology = QtGui.QPushButton(Form)
        self.BrowseShapeInputSymbology.setGeometry(QtCore.QRect(490, 20, 71, 24))
        self.BrowseShapeInputSymbology.setObjectName(_fromUtf8("BrowseShapeInputSymbology"))
        self.comboBoxSelectStdDev = QtGui.QComboBox(Form)
        self.comboBoxSelectStdDev.setEnabled(False)
        self.comboBoxSelectStdDev.setGeometry(QtCore.QRect(440, 160, 121, 22))
        self.comboBoxSelectStdDev.setObjectName(_fromUtf8("comboBoxSelectStdDev"))
        self.comboBoxSelectStdDev.addItem(_fromUtf8(""))
        self.comboBoxSelectStdDev.addItem(_fromUtf8(""))
        self.comboBoxSelectStdDev.addItem(_fromUtf8(""))
        self.comboBoxSelectStdDev.addItem(_fromUtf8(""))
        self.doubleSpinBoxThickness_7 = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBoxThickness_7.setEnabled(False)
        self.doubleSpinBoxThickness_7.setGeometry(QtCore.QRect(450, 260, 51, 22))
        self.doubleSpinBoxThickness_7.setSingleStep(0.25)
        self.doubleSpinBoxThickness_7.setProperty(_fromUtf8("value"), 5.0)
        self.doubleSpinBoxThickness_7.setObjectName(_fromUtf8("doubleSpinBoxThickness_7"))
        self.lineEditManualInterval_4 = QtGui.QLineEdit(Form)
        self.lineEditManualInterval_4.setEnabled(False)
        self.lineEditManualInterval_4.setGeometry(QtCore.QRect(270, 200, 51, 20))
        self.lineEditManualInterval_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditManualInterval_4.setText(_fromUtf8(""))
        self.lineEditManualInterval_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditManualInterval_4.setObjectName(_fromUtf8("lineEditManualInterval_4"))
        self.doubleSpinBoxThickness_6 = QtGui.QDoubleSpinBox(Form)
        self.doubleSpinBoxThickness_6.setEnabled(False)
        self.doubleSpinBoxThickness_6.setGeometry(QtCore.QRect(390, 260, 51, 22))
        self.doubleSpinBoxThickness_6.setSingleStep(0.25)
        self.doubleSpinBoxThickness_6.setProperty(_fromUtf8("value"), 4.0)
        self.doubleSpinBoxThickness_6.setObjectName(_fromUtf8("doubleSpinBoxThickness_6"))
        self.label_18 = QtGui.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(190, 160, 81, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_32 = QtGui.QLabel(Form)
        self.label_32.setGeometry(QtCore.QRect(290, 130, 151, 20))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.ShowDirectioncheckBox = QtGui.QCheckBox(Form)
        self.ShowDirectioncheckBox.setEnabled(True)
        self.ShowDirectioncheckBox.setGeometry(QtCore.QRect(100, 130, 121, 17))
        self.ShowDirectioncheckBox.setChecked(True)
        self.ShowDirectioncheckBox.setObjectName(_fromUtf8("ShowDirectioncheckBox"))

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Form.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Form.reject)
##-------------------------------------------------------------------------##
##-------------------------------------------------------------------------##
        QtCore.QObject.connect(self.comboBoxSelectSymbology, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.enable_disable)
        QtCore.QObject.connect(self.spinBoxClasses, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.enable_disable_class_break)
##-------------------------------------------------------------------------##        
##-------------------------------------------------------------------------##        
        QtCore.QMetaObject.connectSlotsByName(Form)
        
        Form.setTabOrder(self.BrowseShapeLineEdit, self.BrowseShapeInputSymbology)
        Form.setTabOrder(self.BrowseShapeInputSymbology, self.lineEditMinSymbology)
        Form.setTabOrder(self.lineEditMinSymbology, self.lineEditMaxSymbology)
        Form.setTabOrder(self.lineEditMaxSymbology, self.lineEditMeanSymbology)
        Form.setTabOrder(self.lineEditMeanSymbology, self.lineEditStdDevSymbology)
        Form.setTabOrder(self.lineEditStdDevSymbology, self.lineEditNoOfFeaturesSymbology)
        Form.setTabOrder(self.lineEditNoOfFeaturesSymbology, self.ShowDirectioncheckBox)
        Form.setTabOrder(self.ShowDirectioncheckBox, self.comboBoxSelectSymbology)
        Form.setTabOrder(self.comboBoxSelectSymbology, self.spinBoxClasses)
        Form.setTabOrder(self.spinBoxClasses, self.lineEditInterval)
        Form.setTabOrder(self.lineEditInterval, self.comboBoxSelectStdDev)
        Form.setTabOrder(self.comboBoxSelectStdDev, self.lineEditManualInterval_1)
        Form.setTabOrder(self.lineEditManualInterval_1, self.lineEditManualInterval_2)
        Form.setTabOrder(self.lineEditManualInterval_2, self.lineEditManualInterval_3)
        Form.setTabOrder(self.lineEditManualInterval_3, self.lineEditManualInterval_4)
        Form.setTabOrder(self.lineEditManualInterval_4, self.lineEditManualInterval_5)
        Form.setTabOrder(self.lineEditManualInterval_5, self.lineEditManualInterval_6)
        Form.setTabOrder(self.lineEditManualInterval_6, self.lineEditManualInterval_7)
        Form.setTabOrder(self.lineEditManualInterval_7, self.lineEditManualInterval_8)
        Form.setTabOrder(self.lineEditManualInterval_8, self.PushButtonColorSelect_1)
        Form.setTabOrder(self.PushButtonColorSelect_1, self.PushButtonColorSelect_2)
        Form.setTabOrder(self.PushButtonColorSelect_2, self.PushButtonColorSelect_3)
        Form.setTabOrder(self.PushButtonColorSelect_3, self.PushButtonColorSelect_4)
        Form.setTabOrder(self.PushButtonColorSelect_4, self.PushButtonColorSelect_5)
        Form.setTabOrder(self.PushButtonColorSelect_5, self.PushButtonColorSelect_6)
        Form.setTabOrder(self.PushButtonColorSelect_6, self.PushButtonColorSelect_7)
        Form.setTabOrder(self.PushButtonColorSelect_7, self.PushButtonColorSelect_8)
        Form.setTabOrder(self.PushButtonColorSelect_8, self.doubleSpinBoxThickness_1)
        Form.setTabOrder(self.doubleSpinBoxThickness_1, self.doubleSpinBoxThickness_2)
        Form.setTabOrder(self.doubleSpinBoxThickness_2, self.doubleSpinBoxThickness_3)
        Form.setTabOrder(self.doubleSpinBoxThickness_3, self.doubleSpinBoxThickness_4)
        Form.setTabOrder(self.doubleSpinBoxThickness_4, self.doubleSpinBoxThickness_5)
        Form.setTabOrder(self.doubleSpinBoxThickness_5, self.doubleSpinBoxThickness_6)
        Form.setTabOrder(self.doubleSpinBoxThickness_6, self.doubleSpinBoxThickness_7)
        Form.setTabOrder(self.doubleSpinBoxThickness_7, self.doubleSpinBoxThickness_8)
        Form.setTabOrder(self.doubleSpinBoxThickness_8, self.buttonBox)

##--------------------------------------------------------------------------------------##

    def enable_disable(self):
    
        self.ShowDirectioncheckBox.setChecked(True)
        
        if self.comboBoxSelectSymbology.currentText() == "Single Symbol":
            self.spinBoxClasses.setMaximum(99)
            self.spinBoxClasses.setValue(2)
            self.spinBoxClasses.setEnabled(False)
            self.lineEditInterval.setEnabled(False)
            self.comboBoxSelectStdDev.setEnabled(False)
            self.lineEditManualInterval_1.setEnabled(False)            
            self.lineEditManualInterval_2.setEnabled(False)            
            self.lineEditManualInterval_3.setEnabled(False)            
            self.lineEditManualInterval_4.setEnabled(False)            
            self.lineEditManualInterval_5.setEnabled(False)            
            self.lineEditManualInterval_6.setEnabled(False)            
            self.lineEditManualInterval_7.setEnabled(False)            
            self.lineEditManualInterval_8.setEnabled(False)            
            self.PushButtonColorSelect_1.setEnabled(False)            
            self.PushButtonColorSelect_2.setEnabled(False)            
            self.PushButtonColorSelect_3.setEnabled(False)            
            self.PushButtonColorSelect_4.setEnabled(False)            
            self.PushButtonColorSelect_5.setEnabled(False)            
            self.PushButtonColorSelect_6.setEnabled(False)            
            self.PushButtonColorSelect_7.setEnabled(False)            
            self.PushButtonColorSelect_8.setEnabled(False)            
            self.doubleSpinBoxThickness_1.setEnabled(False)            
            self.doubleSpinBoxThickness_2.setEnabled(False)            
            self.doubleSpinBoxThickness_3.setEnabled(False)            
            self.doubleSpinBoxThickness_4.setEnabled(False)            
            self.doubleSpinBoxThickness_5.setEnabled(False)            
            self.doubleSpinBoxThickness_6.setEnabled(False)            
            self.doubleSpinBoxThickness_7.setEnabled(False)            
            self.doubleSpinBoxThickness_8.setEnabled(False)            
        elif self.comboBoxSelectSymbology.currentText() == "Equal Size Classes":
            self.spinBoxClasses.setMaximum(99)
            self.spinBoxClasses.setValue(2)
            self.spinBoxClasses.setEnabled(True)
            self.lineEditInterval.setEnabled(False)
            self.comboBoxSelectStdDev.setEnabled(False)        
            self.lineEditManualInterval_1.setEnabled(False)
            self.lineEditManualInterval_2.setEnabled(False)
            self.lineEditManualInterval_3.setEnabled(False)
            self.lineEditManualInterval_4.setEnabled(False)
            self.lineEditManualInterval_5.setEnabled(False)
            self.lineEditManualInterval_6.setEnabled(False)
            self.lineEditManualInterval_7.setEnabled(False)
            self.lineEditManualInterval_8.setEnabled(False)
            self.PushButtonColorSelect_1.setEnabled(False)
            self.PushButtonColorSelect_2.setEnabled(False)
            self.PushButtonColorSelect_3.setEnabled(False)
            self.PushButtonColorSelect_4.setEnabled(False)
            self.PushButtonColorSelect_5.setEnabled(False)
            self.PushButtonColorSelect_6.setEnabled(False)
            self.PushButtonColorSelect_7.setEnabled(False)
            self.PushButtonColorSelect_8.setEnabled(False)
            self.doubleSpinBoxThickness_1.setEnabled(False)
            self.doubleSpinBoxThickness_2.setEnabled(False)
            self.doubleSpinBoxThickness_3.setEnabled(False)
            self.doubleSpinBoxThickness_4.setEnabled(False)
            self.doubleSpinBoxThickness_5.setEnabled(False)
            self.doubleSpinBoxThickness_6.setEnabled(False)
            self.doubleSpinBoxThickness_7.setEnabled(False)
            self.doubleSpinBoxThickness_8.setEnabled(False)
        elif self.comboBoxSelectSymbology.currentText() == "Equal Interval":
            self.spinBoxClasses.setMaximum(99)
            self.spinBoxClasses.setValue(2)
            self.spinBoxClasses.setEnabled(True)
            self.lineEditInterval.setEnabled(False)
            self.comboBoxSelectStdDev.setEnabled(False)  
            self.lineEditManualInterval_1.setEnabled(False)            
            self.lineEditManualInterval_2.setEnabled(False)            
            self.lineEditManualInterval_3.setEnabled(False)            
            self.lineEditManualInterval_4.setEnabled(False)            
            self.lineEditManualInterval_5.setEnabled(False)            
            self.lineEditManualInterval_6.setEnabled(False)            
            self.lineEditManualInterval_7.setEnabled(False)            
            self.lineEditManualInterval_8.setEnabled(False)            
            self.PushButtonColorSelect_1.setEnabled(False)            
            self.PushButtonColorSelect_2.setEnabled(False)            
            self.PushButtonColorSelect_3.setEnabled(False)            
            self.PushButtonColorSelect_4.setEnabled(False)            
            self.PushButtonColorSelect_5.setEnabled(False)            
            self.PushButtonColorSelect_6.setEnabled(False)            
            self.PushButtonColorSelect_7.setEnabled(False)            
            self.PushButtonColorSelect_8.setEnabled(False)            
            self.doubleSpinBoxThickness_1.setEnabled(False)            
            self.doubleSpinBoxThickness_2.setEnabled(False)            
            self.doubleSpinBoxThickness_3.setEnabled(False)            
            self.doubleSpinBoxThickness_4.setEnabled(False)            
            self.doubleSpinBoxThickness_5.setEnabled(False)            
            self.doubleSpinBoxThickness_6.setEnabled(False)            
            self.doubleSpinBoxThickness_7.setEnabled(False)            
            self.doubleSpinBoxThickness_8.setEnabled(False)            
        elif self.comboBoxSelectSymbology.currentText() == "Defined Interval":
            self.spinBoxClasses.setMaximum(99)
            self.spinBoxClasses.setValue(2)
            self.spinBoxClasses.setEnabled(False)
            self.lineEditInterval.setEnabled(True)
            self.comboBoxSelectStdDev.setEnabled(False)
            self.lineEditManualInterval_1.setEnabled(False)
            self.lineEditManualInterval_2.setEnabled(False)
            self.lineEditManualInterval_3.setEnabled(False)
            self.lineEditManualInterval_4.setEnabled(False)
            self.lineEditManualInterval_5.setEnabled(False)
            self.lineEditManualInterval_6.setEnabled(False)
            self.lineEditManualInterval_7.setEnabled(False)
            self.lineEditManualInterval_8.setEnabled(False)
            self.PushButtonColorSelect_1.setEnabled(False)
            self.PushButtonColorSelect_2.setEnabled(False)
            self.PushButtonColorSelect_3.setEnabled(False)
            self.PushButtonColorSelect_4.setEnabled(False)
            self.PushButtonColorSelect_5.setEnabled(False)
            self.PushButtonColorSelect_6.setEnabled(False)
            self.PushButtonColorSelect_7.setEnabled(False)
            self.PushButtonColorSelect_8.setEnabled(False)
            self.doubleSpinBoxThickness_1.setEnabled(False)
            self.doubleSpinBoxThickness_2.setEnabled(False)
            self.doubleSpinBoxThickness_3.setEnabled(False)
            self.doubleSpinBoxThickness_4.setEnabled(False)
            self.doubleSpinBoxThickness_5.setEnabled(False)
            self.doubleSpinBoxThickness_6.setEnabled(False)
            self.doubleSpinBoxThickness_7.setEnabled(False)
            self.doubleSpinBoxThickness_8.setEnabled(False)
        elif self.comboBoxSelectSymbology.currentText() == "Standard Deviation":
            self.spinBoxClasses.setMaximum(99)
            self.spinBoxClasses.setValue(2)
            self.spinBoxClasses.setEnabled(False)
            self.lineEditInterval.setEnabled(False)
            self.comboBoxSelectStdDev.setEnabled(True)
            self.lineEditManualInterval_1.setEnabled(False)
            self.lineEditManualInterval_2.setEnabled(False)
            self.lineEditManualInterval_3.setEnabled(False)
            self.lineEditManualInterval_4.setEnabled(False)
            self.lineEditManualInterval_5.setEnabled(False)
            self.lineEditManualInterval_6.setEnabled(False)
            self.lineEditManualInterval_7.setEnabled(False)
            self.lineEditManualInterval_8.setEnabled(False)
            self.PushButtonColorSelect_1.setEnabled(False)
            self.PushButtonColorSelect_2.setEnabled(False)
            self.PushButtonColorSelect_3.setEnabled(False)
            self.PushButtonColorSelect_4.setEnabled(False)
            self.PushButtonColorSelect_5.setEnabled(False)
            self.PushButtonColorSelect_6.setEnabled(False)
            self.PushButtonColorSelect_7.setEnabled(False)
            self.PushButtonColorSelect_8.setEnabled(False)
            self.doubleSpinBoxThickness_1.setEnabled(False)
            self.doubleSpinBoxThickness_2.setEnabled(False)
            self.doubleSpinBoxThickness_3.setEnabled(False)
            self.doubleSpinBoxThickness_4.setEnabled(False)
            self.doubleSpinBoxThickness_5.setEnabled(False)
            self.doubleSpinBoxThickness_6.setEnabled(False)
            self.doubleSpinBoxThickness_7.setEnabled(False)
            self.doubleSpinBoxThickness_8.setEnabled(False)
            
        elif self.comboBoxSelectSymbology.currentText() == "Manual Interval":
            self.spinBoxClasses.setMaximum(8)
            self.spinBoxClasses.setValue(2)
            self.spinBoxClasses.setEnabled(True)
            self.lineEditInterval.setEnabled(False)
            self.comboBoxSelectStdDev.setEnabled(False)        
            self.lineEditManualInterval_1.setEnabled(True)
            self.lineEditManualInterval_2.setEnabled(True)
            self.PushButtonColorSelect_1.setEnabled(True)
            self.PushButtonColorSelect_2.setEnabled(True)
            self.doubleSpinBoxThickness_1.setEnabled(True)
            self.doubleSpinBoxThickness_2.setEnabled(True)

    def enable_disable_class_break(self):
        if self.comboBoxSelectSymbology.currentText() == "Manual Interval":
            if self.spinBoxClasses.value() >= 2:
                self.lineEditManualInterval_3.setText("")
                self.lineEditManualInterval_4.setText("")
                self.lineEditManualInterval_5.setText("")
                self.lineEditManualInterval_6.setText("")
                self.lineEditManualInterval_7.setText("")
                self.lineEditManualInterval_8.setText("")
                self.lineEditManualInterval_3.setEnabled(False)
                self.PushButtonColorSelect_3.setEnabled(False)
                self.doubleSpinBoxThickness_3.setEnabled(False)
                self.lineEditManualInterval_4.setEnabled(False)
                self.lineEditManualInterval_5.setEnabled(False)
                self.lineEditManualInterval_6.setEnabled(False)
                self.lineEditManualInterval_7.setEnabled(False)
                self.lineEditManualInterval_8.setEnabled(False)
                self.PushButtonColorSelect_4.setEnabled(False)
                self.PushButtonColorSelect_5.setEnabled(False)
                self.PushButtonColorSelect_6.setEnabled(False)
                self.PushButtonColorSelect_7.setEnabled(False)
                self.PushButtonColorSelect_8.setEnabled(False)
                self.doubleSpinBoxThickness_4.setEnabled(False)
                self.doubleSpinBoxThickness_5.setEnabled(False)
                self.doubleSpinBoxThickness_6.setEnabled(False)
                self.doubleSpinBoxThickness_7.setEnabled(False)
                self.doubleSpinBoxThickness_8.setEnabled(False)         
            if self.spinBoxClasses.value() >= 3:
                self.lineEditManualInterval_3.setEnabled(True)
                self.PushButtonColorSelect_3.setEnabled(True)
                self.doubleSpinBoxThickness_3.setEnabled(True)
            if self.spinBoxClasses.value() >= 4:
                self.lineEditManualInterval_4.setEnabled(True)
                self.PushButtonColorSelect_4.setEnabled(True)
                self.doubleSpinBoxThickness_4.setEnabled(True)
            if self.spinBoxClasses.value() >= 5:
                self.lineEditManualInterval_5.setEnabled(True)
                self.PushButtonColorSelect_5.setEnabled(True)
                self.doubleSpinBoxThickness_5.setEnabled(True)
            if self.spinBoxClasses.value() >= 6:
                self.lineEditManualInterval_6.setEnabled(True)
                self.PushButtonColorSelect_6.setEnabled(True)
                self.doubleSpinBoxThickness_6.setEnabled(True)        
            if self.spinBoxClasses.value() >= 7:
                self.lineEditManualInterval_7.setEnabled(True)
                self.PushButtonColorSelect_7.setEnabled(True)
                self.doubleSpinBoxThickness_7.setEnabled(True)
            if self.spinBoxClasses.value() >= 8:
                self.lineEditManualInterval_8.setEnabled(True)
                self.PushButtonColorSelect_8.setEnabled(True)
                self.doubleSpinBoxThickness_8.setEnabled(True)        
        
##--------------------------------------------------------------------------------------##                
        
    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Symbology for flow lines", None, QtGui.QApplication.UnicodeUTF8))
        self.PushButtonColorSelect_3.setText(QtGui.QApplication.translate("Form", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Form", "* Input shapefile must be created with Flow Mapper or include \"magnitude\" field.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Form", "No. of Feat. :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectSymbology.setItemText(0, QtGui.QApplication.translate("Form", "Single Symbol", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectSymbology.setItemText(1, QtGui.QApplication.translate("Form", "Equal Size Classes", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectSymbology.setItemText(2, QtGui.QApplication.translate("Form", "Equal Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectSymbology.setItemText(3, QtGui.QApplication.translate("Form", "Defined Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectSymbology.setItemText(4, QtGui.QApplication.translate("Form", "Standard Deviation", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectSymbology.setItemText(5, QtGui.QApplication.translate("Form", "Manual Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.PushButtonColorSelect_7.setText(QtGui.QApplication.translate("Form", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Form", "Thickness :", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditInterval.setText(QtGui.QApplication.translate("Form", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.PushButtonColorSelect_8.setText(QtGui.QApplication.translate("Form", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Form", " Std. Dev. :", None, QtGui.QApplication.UnicodeUTF8))
        self.PushButtonColorSelect_6.setText(QtGui.QApplication.translate("Form", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.PushButtonColorSelect_4.setText(QtGui.QApplication.translate("Form", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Form", "No. of classes :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Form", " Min. :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "Class Interval :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_01.setText(QtGui.QApplication.translate("Form", "Select shapefile storing flow lines :", None, QtGui.QApplication.UnicodeUTF8))
        self.PushButtonColorSelect_2.setText(QtGui.QApplication.translate("Form", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Form", " Mean :", None, QtGui.QApplication.UnicodeUTF8))
        self.PushButtonColorSelect_1.setText(QtGui.QApplication.translate("Form", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Form", " Max. :", None, QtGui.QApplication.UnicodeUTF8))
        self.PushButtonColorSelect_5.setText(QtGui.QApplication.translate("Form", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Form", "Class break :", None, QtGui.QApplication.UnicodeUTF8))
        self.BrowseShapeInputSymbology.setText(QtGui.QApplication.translate("Form", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectStdDev.setItemText(0, QtGui.QApplication.translate("Form", "1/4 Std. Dev.", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectStdDev.setItemText(1, QtGui.QApplication.translate("Form", "1/2 Std. Dev.", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectStdDev.setItemText(2, QtGui.QApplication.translate("Form", "1 Std. Dev.", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectStdDev.setItemText(3, QtGui.QApplication.translate("Form", "2 Std. Dev.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "Class interval :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Form", " Select representation type :", None, QtGui.QApplication.UnicodeUTF8))
        self.ShowDirectioncheckBox.setText(QtGui.QApplication.translate("Form", "Show flow direction", None, QtGui.QApplication.UnicodeUTF8))

import resources
