# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_flowmapper.ui'
#
# Created: Wed Dec 18 02:12:14 2013
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_FlowMapper(object):
    def setupUi(self, FlowMapper):
        FlowMapper.setObjectName(_fromUtf8("FlowMapper"))
        FlowMapper.setWindowModality(QtCore.Qt.NonModal)
        FlowMapper.resize(540, 400)
        FlowMapper.setMinimumSize(QtCore.QSize(540, 400))
        FlowMapper.setMaximumSize(QtCore.QSize(540, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/flowmapper/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FlowMapper.setWindowIcon(icon)
        FlowMapper.setModal(False)
        self.buttonBox = QtGui.QDialogButtonBox(FlowMapper)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setGeometry(QtCore.QRect(365, 360, 160, 25))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.BrowseShapeLineEdit = QtGui.QLineEdit(FlowMapper)
        self.BrowseShapeLineEdit.setEnabled(False)
        self.BrowseShapeLineEdit.setGeometry(QtCore.QRect(239, 170, 201, 20))
        self.BrowseShapeLineEdit.setText(_fromUtf8(""))
        self.BrowseShapeLineEdit.setObjectName(_fromUtf8("BrowseShapeLineEdit"))
        self.BrowseShape = QtGui.QPushButton(FlowMapper)
        self.BrowseShape.setGeometry(QtCore.QRect(450, 170, 75, 23))
        self.BrowseShape.setObjectName(_fromUtf8("BrowseShape"))
        self.BrowseNodesLineEdit = QtGui.QLineEdit(FlowMapper)
        self.BrowseNodesLineEdit.setEnabled(False)
        self.BrowseNodesLineEdit.setGeometry(QtCore.QRect(239, 20, 201, 20))
        self.BrowseNodesLineEdit.setText(_fromUtf8(""))
        self.BrowseNodesLineEdit.setObjectName(_fromUtf8("BrowseNodesLineEdit"))
        self.BrowseNodes = QtGui.QPushButton(FlowMapper)
        self.BrowseNodes.setGeometry(QtCore.QRect(450, 20, 75, 24))
        self.BrowseNodes.setObjectName(_fromUtf8("BrowseNodes"))
        self.label_02 = QtGui.QLabel(FlowMapper)
        self.label_02.setGeometry(QtCore.QRect(10, 110, 150, 20))
        self.label_02.setObjectName(_fromUtf8("label_02"))
        self.label_01 = QtGui.QLabel(FlowMapper)
        self.label_01.setGeometry(QtCore.QRect(10, 20, 180, 20))
        self.label_01.setObjectName(_fromUtf8("label_01"))
        self.BrowseMatrixLineEdit = QtGui.QLineEdit(FlowMapper)
        self.BrowseMatrixLineEdit.setEnabled(False)
        self.BrowseMatrixLineEdit.setGeometry(QtCore.QRect(239, 110, 201, 20))
        self.BrowseMatrixLineEdit.setText(_fromUtf8(""))
        self.BrowseMatrixLineEdit.setObjectName(_fromUtf8("BrowseMatrixLineEdit"))
        self.BrowseMatrix = QtGui.QPushButton(FlowMapper)
        self.BrowseMatrix.setGeometry(QtCore.QRect(450, 110, 75, 23))
        self.BrowseMatrix.setObjectName(_fromUtf8("BrowseMatrix"))
        self.label_04 = QtGui.QLabel(FlowMapper)
        self.label_04.setGeometry(QtCore.QRect(10, 170, 180, 20))
        self.label_04.setObjectName(_fromUtf8("label_04"))
        self.label_03 = QtGui.QLabel(FlowMapper)
        self.label_03.setGeometry(QtCore.QRect(10, 140, 101, 20))
        self.label_03.setObjectName(_fromUtf8("label_03"))
        self.NetRadioButton = QtGui.QRadioButton(FlowMapper)
        self.NetRadioButton.setGeometry(QtCore.QRect(400, 140, 41, 17))
        self.NetRadioButton.setChecked(True)
        self.NetRadioButton.setObjectName(_fromUtf8("NetRadioButton"))
        self.GrossRadioButton = QtGui.QRadioButton(FlowMapper)
        self.GrossRadioButton.setGeometry(QtCore.QRect(330, 140, 51, 17))
        self.GrossRadioButton.setObjectName(_fromUtf8("GrossRadioButton"))
        self.TwowayRadioButton = QtGui.QRadioButton(FlowMapper)
        self.TwowayRadioButton.setGeometry(QtCore.QRect(240, 140, 71, 17))
        self.TwowayRadioButton.setCheckable(True)
        self.TwowayRadioButton.setChecked(False)
        self.TwowayRadioButton.setObjectName(_fromUtf8("TwowayRadioButton"))
        self.comboBox = QtGui.QComboBox(FlowMapper)
        self.comboBox.setGeometry(QtCore.QRect(350, 50, 91, 22))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.label_5 = QtGui.QLabel(FlowMapper)
        self.label_5.setGeometry(QtCore.QRect(240, 50, 111, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.Add2MapcheckBox = QtGui.QCheckBox(FlowMapper)
        self.Add2MapcheckBox.setEnabled(True)
        self.Add2MapcheckBox.setGeometry(QtCore.QRect(10, 290, 201, 17))
        self.Add2MapcheckBox.setChecked(True)
        self.Add2MapcheckBox.setObjectName(_fromUtf8("Add2MapcheckBox"))
        self.comboBoxSelectSymbology = QtGui.QComboBox(FlowMapper)
        self.comboBoxSelectSymbology.setEnabled(True)
        self.comboBoxSelectSymbology.setGeometry(QtCore.QRect(393, 290, 131, 22))
        self.comboBoxSelectSymbology.setObjectName(_fromUtf8("comboBoxSelectSymbology"))
        self.comboBoxSelectSymbology.addItem(_fromUtf8(""))
        self.comboBoxSelectSymbology.addItem(_fromUtf8(""))
        self.comboBoxSelectSymbology.addItem(_fromUtf8(""))
        self.comboBoxSelectSymbology.addItem(_fromUtf8(""))
        self.comboBoxSelectSymbology.addItem(_fromUtf8(""))
        self.spinBoxClasses = QtGui.QSpinBox(FlowMapper)
        self.spinBoxClasses.setEnabled(False)
        self.spinBoxClasses.setGeometry(QtCore.QRect(90, 320, 51, 22))
        self.spinBoxClasses.setMinimum(2)
        self.spinBoxClasses.setProperty(_fromUtf8("value"), 2)
        self.spinBoxClasses.setObjectName(_fromUtf8("spinBoxClasses"))
        self.lineEditInterval = QtGui.QLineEdit(FlowMapper)
        self.lineEditInterval.setEnabled(False)
        self.lineEditInterval.setGeometry(QtCore.QRect(240, 320, 51, 20))
        self.lineEditInterval.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditInterval.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEditInterval.setObjectName(_fromUtf8("lineEditInterval"))
        self.label_6 = QtGui.QLabel(FlowMapper)
        self.label_6.setGeometry(QtCore.QRect(160, 320, 81, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(FlowMapper)
        self.label_7.setGeometry(QtCore.QRect(10, 320, 81, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.comboBoxSelectStdDev = QtGui.QComboBox(FlowMapper)
        self.comboBoxSelectStdDev.setEnabled(False)
        self.comboBoxSelectStdDev.setGeometry(QtCore.QRect(393, 320, 131, 22))
        self.comboBoxSelectStdDev.setObjectName(_fromUtf8("comboBoxSelectStdDev"))
        self.comboBoxSelectStdDev.addItem(_fromUtf8(""))
        self.comboBoxSelectStdDev.addItem(_fromUtf8(""))
        self.comboBoxSelectStdDev.addItem(_fromUtf8(""))
        self.comboBoxSelectStdDev.addItem(_fromUtf8(""))
        self.label_8 = QtGui.QLabel(FlowMapper)
        self.label_8.setGeometry(QtCore.QRect(310, 320, 81, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.ShowDirectioncheckBox = QtGui.QCheckBox(FlowMapper)
        self.ShowDirectioncheckBox.setEnabled(True)
        self.ShowDirectioncheckBox.setGeometry(QtCore.QRect(240, 290, 121, 17))
        self.ShowDirectioncheckBox.setChecked(True)
        self.ShowDirectioncheckBox.setObjectName(_fromUtf8("ShowDirectioncheckBox"))
        self.BrowseNodeNames = QtGui.QPushButton(FlowMapper)
        self.BrowseNodeNames.setEnabled(False)
        self.BrowseNodeNames.setGeometry(QtCore.QRect(450, 80, 75, 23))
        self.BrowseNodeNames.setObjectName(_fromUtf8("BrowseNodeNames"))
        self.label_3 = QtGui.QLabel(FlowMapper)
        self.label_3.setEnabled(False)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 161, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.BrowseNodeNamesLineEdit = QtGui.QLineEdit(FlowMapper)
        self.BrowseNodeNamesLineEdit.setEnabled(False)
        self.BrowseNodeNamesLineEdit.setGeometry(QtCore.QRect(239, 80, 201, 20))
        self.BrowseNodeNamesLineEdit.setText(_fromUtf8(""))
        self.BrowseNodeNamesLineEdit.setObjectName(_fromUtf8("BrowseNodeNamesLineEdit"))
        self.IncludeNodeNamescheckBox = QtGui.QCheckBox(FlowMapper)
        self.IncludeNodeNamescheckBox.setEnabled(True)
        self.IncludeNodeNamescheckBox.setGeometry(QtCore.QRect(10, 50, 221, 17))
        self.IncludeNodeNamescheckBox.setChecked(False)
        self.IncludeNodeNamescheckBox.setObjectName(_fromUtf8("IncludeNodeNamescheckBox"))
        self.label_9 = QtGui.QLabel(FlowMapper)
        self.label_9.setEnabled(False)
        self.label_9.setGeometry(QtCore.QRect(10, 230, 191, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.BrowseShapeNodesLineEdit = QtGui.QLineEdit(FlowMapper)
        self.BrowseShapeNodesLineEdit.setEnabled(False)
        self.BrowseShapeNodesLineEdit.setGeometry(QtCore.QRect(239, 230, 201, 20))
        self.BrowseShapeNodesLineEdit.setText(_fromUtf8(""))
        self.BrowseShapeNodesLineEdit.setObjectName(_fromUtf8("BrowseShapeNodesLineEdit"))
        self.BrowseShapeNodes = QtGui.QPushButton(FlowMapper)
        self.BrowseShapeNodes.setEnabled(False)
        self.BrowseShapeNodes.setGeometry(QtCore.QRect(450, 230, 75, 23))
        self.BrowseShapeNodes.setObjectName(_fromUtf8("BrowseShapeNodes"))
        self.CreateFlowNodescheckBox = QtGui.QCheckBox(FlowMapper)
        self.CreateFlowNodescheckBox.setEnabled(True)
        self.CreateFlowNodescheckBox.setGeometry(QtCore.QRect(10, 200, 201, 17))
        self.CreateFlowNodescheckBox.setChecked(False)
        self.CreateFlowNodescheckBox.setObjectName(_fromUtf8("CreateFlowNodescheckBox"))
        self.AddNodes2MapcheckBox = QtGui.QCheckBox(FlowMapper)
        self.AddNodes2MapcheckBox.setEnabled(False)
        self.AddNodes2MapcheckBox.setGeometry(QtCore.QRect(10, 260, 211, 17))
        self.AddNodes2MapcheckBox.setChecked(False)
        self.AddNodes2MapcheckBox.setObjectName(_fromUtf8("AddNodes2MapcheckBox"))
        self.DifNodeSymbologycheckBox = QtGui.QCheckBox(FlowMapper)
        self.DifNodeSymbologycheckBox.setEnabled(False)
        self.DifNodeSymbologycheckBox.setGeometry(QtCore.QRect(240, 260, 291, 20))
        self.DifNodeSymbologycheckBox.setChecked(False)
        self.DifNodeSymbologycheckBox.setObjectName(_fromUtf8("DifNodeSymbologycheckBox"))

        self.retranslateUi(FlowMapper)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), FlowMapper.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), FlowMapper.reject)
        QtCore.QObject.connect(self.Add2MapcheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.comboBoxSelectSymbology.setEnabled)
        QtCore.QObject.connect(self.comboBoxSelectSymbology, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.comboBoxSelectSymbology.setCurrentIndex)
        QtCore.QObject.connect(self.GrossRadioButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.ShowDirectioncheckBox.toggle)
        QtCore.QObject.connect(self.GrossRadioButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.ShowDirectioncheckBox.setDisabled)
        QtCore.QObject.connect(self.TwowayRadioButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.ShowDirectioncheckBox.setEnabled)
        QtCore.QObject.connect(self.NetRadioButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.ShowDirectioncheckBox.setEnabled)
        QtCore.QObject.connect(self.IncludeNodeNamescheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label_3.setEnabled)
        QtCore.QObject.connect(self.IncludeNodeNamescheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.BrowseNodeNames.setEnabled)
        QtCore.QObject.connect(self.CreateFlowNodescheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.AddNodes2MapcheckBox.setEnabled)
        QtCore.QObject.connect(self.CreateFlowNodescheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.AddNodes2MapcheckBox.setChecked)
        QtCore.QObject.connect(self.CreateFlowNodescheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.BrowseShapeNodes.setEnabled)
        QtCore.QObject.connect(self.CreateFlowNodescheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.label_9.setEnabled)
        QtCore.QObject.connect(self.CreateFlowNodescheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.DifNodeSymbologycheckBox.setChecked)
        QtCore.QObject.connect(self.CreateFlowNodescheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.DifNodeSymbologycheckBox.setEnabled)
        QtCore.QObject.connect(self.AddNodes2MapcheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.DifNodeSymbologycheckBox.setChecked)
        QtCore.QObject.connect(self.AddNodes2MapcheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.DifNodeSymbologycheckBox.setEnabled)

#----------------------------------------------------------------------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------#
        QtCore.QObject.connect(self.Add2MapcheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.comboBoxSelectSymbology.setEnabled)
        QtCore.QObject.connect(self.Add2MapcheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.reset_enable_disable_state)
        QtCore.QObject.connect(self.GrossRadioButton, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.uncheck_ShowDirectioncheckBox)
        QtCore.QObject.connect(self.comboBoxSelectSymbology, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.enable_disable)
#----------------------------------------------------------------------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------#        
          
        QtCore.QMetaObject.connectSlotsByName(FlowMapper)

        FlowMapper.setTabOrder(self.BrowseNodesLineEdit, self.BrowseNodes)
        FlowMapper.setTabOrder(self.BrowseNodes, self.IncludeNodeNamescheckBox)
        FlowMapper.setTabOrder(self.IncludeNodeNamescheckBox, self.comboBox)
        FlowMapper.setTabOrder(self.comboBox, self.BrowseNodeNamesLineEdit)
        FlowMapper.setTabOrder(self.BrowseNodeNamesLineEdit, self.BrowseNodeNames)
        FlowMapper.setTabOrder(self.BrowseNodeNames, self.BrowseMatrixLineEdit)
        FlowMapper.setTabOrder(self.BrowseMatrixLineEdit, self.BrowseMatrix)
        FlowMapper.setTabOrder(self.BrowseMatrix, self.TwowayRadioButton)
        FlowMapper.setTabOrder(self.TwowayRadioButton, self.GrossRadioButton)
        FlowMapper.setTabOrder(self.GrossRadioButton, self.NetRadioButton)
        FlowMapper.setTabOrder(self.NetRadioButton, self.BrowseShapeLineEdit)
        FlowMapper.setTabOrder(self.BrowseShapeLineEdit, self.BrowseShape)
        FlowMapper.setTabOrder(self.BrowseShape, self.CreateFlowNodescheckBox)
        FlowMapper.setTabOrder(self.CreateFlowNodescheckBox, self.BrowseShapeNodesLineEdit)
        FlowMapper.setTabOrder(self.BrowseShapeNodesLineEdit, self.BrowseShapeNodes)
        FlowMapper.setTabOrder(self.BrowseShapeNodes, self.AddNodes2MapcheckBox)
        FlowMapper.setTabOrder(self.AddNodes2MapcheckBox, self.DifNodeSymbologycheckBox)
        FlowMapper.setTabOrder(self.DifNodeSymbologycheckBox, self.Add2MapcheckBox)
        FlowMapper.setTabOrder(self.Add2MapcheckBox, self.ShowDirectioncheckBox)
        FlowMapper.setTabOrder(self.ShowDirectioncheckBox, self.comboBoxSelectSymbology)
        FlowMapper.setTabOrder(self.comboBoxSelectSymbology, self.spinBoxClasses)
        FlowMapper.setTabOrder(self.spinBoxClasses, self.lineEditInterval)
        FlowMapper.setTabOrder(self.lineEditInterval, self.comboBoxSelectStdDev)
        FlowMapper.setTabOrder(self.comboBoxSelectStdDev, self.buttonBox)
        
        

#----------------------------------------------------------------------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------#
    def reset_enable_disable_state(self):
        self.comboBoxSelectSymbology.setCurrentIndex(0)
        self.spinBoxClasses.setEnabled(False)
        self.lineEditInterval.setEnabled(False)
        self.comboBoxSelectStdDev.setEnabled(False)

        if self.GrossRadioButton.isChecked() == False and self.Add2MapcheckBox.isChecked() == True:
            self.ShowDirectioncheckBox.setEnabled(True)
            self.ShowDirectioncheckBox.setChecked(True)
        elif self.GrossRadioButton.isChecked() == False and self.Add2MapcheckBox.isChecked() == False:
            self.ShowDirectioncheckBox.setEnabled(False)
            self.ShowDirectioncheckBox.setChecked(False)      
        
    def enable_disable(self):
        if self.comboBoxSelectSymbology.currentText() == "Single Symbol":
            self.spinBoxClasses.setEnabled(False)
            self.lineEditInterval.setEnabled(False)
            self.comboBoxSelectStdDev.setEnabled(False)
            if self.GrossRadioButton.isChecked() == False and self.Add2MapcheckBox.isChecked() == True:
                self.ShowDirectioncheckBox.setEnabled(True)
                self.ShowDirectioncheckBox.setChecked(True)
            elif self.GrossRadioButton.isChecked() == False and self.Add2MapcheckBox.isChecked() == False:
                self.ShowDirectioncheckBox.setEnabled(False)
                self.ShowDirectioncheckBox.setChecked(False)      
        
        elif self.comboBoxSelectSymbology.currentText() == "Equal Size Classes":
            self.spinBoxClasses.setEnabled(True)
            self.lineEditInterval.setEnabled(False)
            self.comboBoxSelectStdDev.setEnabled(False)            
            if self.GrossRadioButton.isChecked() == False and self.Add2MapcheckBox.isChecked() == True:
                self.ShowDirectioncheckBox.setEnabled(True)
                self.ShowDirectioncheckBox.setChecked(True)
            elif self.GrossRadioButton.isChecked() == False and self.Add2MapcheckBox.isChecked() == False:
                self.ShowDirectioncheckBox.setEnabled(False)
                self.ShowDirectioncheckBox.setChecked(False)      
            
        elif self.comboBoxSelectSymbology.currentText() == "Equal Interval":
            self.spinBoxClasses.setEnabled(True)
            self.lineEditInterval.setEnabled(False)
            self.comboBoxSelectStdDev.setEnabled(False)  
            if self.GrossRadioButton.isChecked() == False and self.Add2MapcheckBox.isChecked() == True:
                self.ShowDirectioncheckBox.setEnabled(True)
                self.ShowDirectioncheckBox.setChecked(True)
            elif self.GrossRadioButton.isChecked() == False and self.Add2MapcheckBox.isChecked() == False:
                self.ShowDirectioncheckBox.setEnabled(False)
                self.ShowDirectioncheckBox.setChecked(False)      
            
        elif self.comboBoxSelectSymbology.currentText() == "Defined Interval":
            self.spinBoxClasses.setEnabled(False)
            self.lineEditInterval.setEnabled(True)
            self.comboBoxSelectStdDev.setEnabled(False)            
            if self.GrossRadioButton.isChecked() == False and self.Add2MapcheckBox.isChecked() == True:
                self.ShowDirectioncheckBox.setEnabled(True)
                self.ShowDirectioncheckBox.setChecked(True)
            elif self.GrossRadioButton.isChecked() == False and self.Add2MapcheckBox.isChecked() == False:
                self.ShowDirectioncheckBox.setEnabled(False)
                self.ShowDirectioncheckBox.setChecked(False)      
        
        elif self.comboBoxSelectSymbology.currentText() == "Standard Deviation":
            self.spinBoxClasses.setEnabled(False)
            self.lineEditInterval.setEnabled(False)
            self.comboBoxSelectStdDev.setEnabled(True)
            if self.GrossRadioButton.isChecked() == False and self.Add2MapcheckBox.isChecked() == True:
                self.ShowDirectioncheckBox.setEnabled(True)
                self.ShowDirectioncheckBox.setChecked(True)
            elif self.GrossRadioButton.isChecked() == False and self.Add2MapcheckBox.isChecked() == False:
                self.ShowDirectioncheckBox.setEnabled(False)
                self.ShowDirectioncheckBox.setChecked(False)      
            
    def uncheck_ShowDirectioncheckBox(self):
        self.ShowDirectioncheckBox.setChecked(False)
#----------------------------------------------------------------------------------------------------------------------------------------#
#----------------------------------------------------------------------------------------------------------------------------------------#        
        
        
    def retranslateUi(self, FlowMapper):
        FlowMapper.setWindowTitle(QtGui.QApplication.translate("FlowMapper", "Generate flow lines and nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.BrowseShape.setText(QtGui.QApplication.translate("FlowMapper", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.BrowseNodes.setText(QtGui.QApplication.translate("FlowMapper", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_02.setText(QtGui.QApplication.translate("FlowMapper", "Select file storing flow matrix :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_01.setText(QtGui.QApplication.translate("FlowMapper", "Select file storing node coordinates :", None, QtGui.QApplication.UnicodeUTF8))
        self.BrowseMatrix.setText(QtGui.QApplication.translate("FlowMapper", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_04.setText(QtGui.QApplication.translate("FlowMapper", "Output shapefile to store flow lines :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_03.setText(QtGui.QApplication.translate("FlowMapper", "Select flow type :", None, QtGui.QApplication.UnicodeUTF8))
        self.NetRadioButton.setText(QtGui.QApplication.translate("FlowMapper", "Net", None, QtGui.QApplication.UnicodeUTF8))
        self.GrossRadioButton.setText(QtGui.QApplication.translate("FlowMapper", "Gross", None, QtGui.QApplication.UnicodeUTF8))
        self.TwowayRadioButton.setText(QtGui.QApplication.translate("FlowMapper", "Two Way", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("FlowMapper", "Geographic", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("FlowMapper", "Cartesian", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("FlowMapper", "Node coordinates are", None, QtGui.QApplication.UnicodeUTF8))
        self.Add2MapcheckBox.setText(QtGui.QApplication.translate("FlowMapper", "Add flow lines to map after creating", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectSymbology.setItemText(0, QtGui.QApplication.translate("FlowMapper", "Single Symbol", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectSymbology.setItemText(1, QtGui.QApplication.translate("FlowMapper", "Equal Size Classes", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectSymbology.setItemText(2, QtGui.QApplication.translate("FlowMapper", "Equal Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectSymbology.setItemText(3, QtGui.QApplication.translate("FlowMapper", "Defined Interval", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectSymbology.setItemText(4, QtGui.QApplication.translate("FlowMapper", "Standard Deviation", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditInterval.setText(QtGui.QApplication.translate("FlowMapper", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("FlowMapper", "Class interval :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("FlowMapper", "No. of classes :", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectStdDev.setItemText(0, QtGui.QApplication.translate("FlowMapper", "1/4 Std. Dev.", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectStdDev.setItemText(1, QtGui.QApplication.translate("FlowMapper", "1/2 Std. Dev.", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectStdDev.setItemText(2, QtGui.QApplication.translate("FlowMapper", "1 Std. Dev.", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxSelectStdDev.setItemText(3, QtGui.QApplication.translate("FlowMapper", "2 Std. Dev.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("FlowMapper", "Class interval :", None, QtGui.QApplication.UnicodeUTF8))
        self.ShowDirectioncheckBox.setText(QtGui.QApplication.translate("FlowMapper", "Show flow direction", None, QtGui.QApplication.UnicodeUTF8))
        self.BrowseNodeNames.setText(QtGui.QApplication.translate("FlowMapper", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("FlowMapper", "Select file storing node names :", None, QtGui.QApplication.UnicodeUTF8))
        self.IncludeNodeNamescheckBox.setText(QtGui.QApplication.translate("FlowMapper", "Include node names in output shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("FlowMapper", "Output shapefile to store flow nodes :", None, QtGui.QApplication.UnicodeUTF8))
        self.BrowseShapeNodes.setText(QtGui.QApplication.translate("FlowMapper", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.CreateFlowNodescheckBox.setText(QtGui.QApplication.translate("FlowMapper", "Create shapefile to store flow nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.AddNodes2MapcheckBox.setText(QtGui.QApplication.translate("FlowMapper", "Add flow nodes to map after creating", None, QtGui.QApplication.UnicodeUTF8))
        self.DifNodeSymbologycheckBox.setText(QtGui.QApplication.translate("FlowMapper", "Differentiate node symbology by flow gain or flow loss", None, QtGui.QApplication.UnicodeUTF8))

import resources
